# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Linter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-renovate:
    name: Lint Renovate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install node
      uses: actions/setup-node@v3

    - name: Install Renovate
      run: npm install --global renovate

    - name: Validate base renovate config
      run: renovate-config-validator renovate.json

    - name: Validate renovate config for manual updates
      run: renovate-config-validator renovate-manual.json
